from enum import Enum


class RecommendedAction(str, Enum):
    USE_STANDARD_SCOPE_ITEM = "USE_STANDARD_SCOPE_ITEM"
    REDUCE_CUSTOM_FIELDS = "REDUCE_CUSTOM_FIELDS"
    MIGRATE_USER_EXIT_TO_BADI = "MIGRATE_USER_EXIT_TO_BADI"
    ACTIVATE_SCOPE_ITEM = "ACTIVATE_SCOPE_ITEM"
    MANUAL_REVIEW = "MANUAL_REVIEW"

